name: gsloution_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  device_info_plus: ^11.0.0
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  get: ^4.6.6
  logger: ^2.4.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  country_code_picker: ^3.1.0
  cached_network_image: ^3.4.1
  flutter_form_builder: ^9.5.0
  google_fonts: ^6.2.1
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: RobotoBlackItalic
      fonts:
        - asset: assets/fonts/Roboto-BlackItalic.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoBoldItalic
      fonts:
        - asset: assets/fonts/Roboto-BoldItalic.ttf
    - family: RobotoItalic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoLightItalic
      fonts:
        - asset: assets/fonts/Roboto-LightItalic.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoMediumItalic
      fonts:
        - asset: assets/fonts/Roboto-MediumItalic.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
    - family: RobotoThinItalic
      fonts:
        - asset: assets/fonts/Roboto-ThinItalic.ttf
  uses-material-design: true
  assets:
    - assets/images/
